  language: cpp

  group: stable
  os: 
     - linux
  dist: xenial
  addons:
    apt:
      packages:
         - libboost-all-dev
         - build-essential 
         - pkg-config 
         - libssl-dev 
         - libzmq3-dev 
         - libunbound-dev 
         - libminiupnpc-dev 
         - libreadline6-dev 
         - libldns-dev
         - qt5-default

  before_install: 
            - chmod +x build.sh
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get clean; fi
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install make qt5-default cmake build-essential libboost-all-dev pkg-config libssl-dev libzmq3-dev libunbound-dev libsodium-dev libminiupnpc-dev libreadline6-dev libldns-dev; fi
  script:
            ./build.sh

